@BASE_URL = http://localhost:3333
@USER_ID = dec63b04-b766-44fc-950b-ebdc050bf8ba

# @name create_user
POST {{BASE_URL}}/users/create
Content-Type: application/json

{
  "name": "John Doe 2",
  "email": "johndoe2@mail.com"
}

###

# @name find_all_users
GET {{BASE_URL}}/users
Content-Type: application/json

###

# @name update_user
PATCH {{BASE_URL}}/users/{{USER_ID}}
content-type: application/json

{
  "name": "John Doe Updated",
  "email": "johndoeupdated@mail.com"
}

### 

# @name delete_user
DELETE {{BASE_URL}}/users/{{USER_ID}}
Content-Type: application/json